ai_model: deepseek-chat
database: data/inventory.db
openai_api_key:  
openai_base_url: https://api.deepseek.com/v1
theme:
  alpha: 102
  alpha_percent: 40
  auto_font: false
  background_color: '#ffffff'
  background_image: D:/图片/片/D (1).jpg
  background_type: image
  font_color: '#000000'
